title: Aditya Astro Vision
#description: Coming soon

url: http://adityaastrovision.com/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: About
   url: /about
 - title: Blog
   url: /blog
 - title: Contact
   url: /contact

social:
   email: pnaditya@gmail.com

google_analytics: "UA-58263416-1"
